<a href="https://colab.research.google.com/github/DOOryUniverse/UBION-Big-data-analyst-study/blob/main/DART_%EA%B8%B0%EC%97%85_%EC%9E%AC%EB%AC%B4_%EA%B3%B5%EC%8B%9C%EC%9E%90%EB%A3%8C_%EA%B0%80%EC%A0%B8%EC%98%A4%EA%B8%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install opendartreader

Collecting opendartreader
  Downloading OpenDartReader-0.1.6-py3-none-any.whl (19 kB)
Requirement already satisfied: pandas>=0.19.2 in /usr/local/lib/python3.7/dist-packages (from opendartreader) (1.3.5)
Requirement already satisfied: lxml in /usr/local/lib/python3.7/dist-packages (from opendartreader) (4.2.6)
Collecting requests-file
  Downloading requests_file-1.5.1-py2.py3-none-any.whl (3.7 kB)
Requirement already satisfied: requests>=2.3.0 in /usr/local/lib/python3.7/dist-packages (from opendartreader) (2.23.0)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.19.2->opendartreader) (2.8.2)
Requirement already satisfied: numpy>=1.17.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.19.2->opendartreader) (1.19.5)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.19.2->opendartreader) (2018.9)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas>=0.19.2->opendartreader) (1.15.0)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests>=2.3.0->opendartreader) (1.24.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests>=2.3.0->opendartreader) (2021.10.8)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests>=2.3.0->opendartreader) (2.10)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests>=2.3.0->opendartreader) (3.0.4)
Installing collected packages: requests-file, opendartreader
Successfully installed opendartreader-0.1.6 requests-file-1.5.1

In [ ]:
!pip install --upgrade opendartreader

Requirement already satisfied: opendartreader in /usr/local/lib/python3.7/dist-packages (0.1.6)
Requirement already satisfied: requests>=2.3.0 in /usr/local/lib/python3.7/dist-packages (from opendartreader) (2.23.0)
Requirement already satisfied: lxml in /usr/local/lib/python3.7/dist-packages (from opendartreader) (4.2.6)
Requirement already satisfied: pandas>=0.19.2 in /usr/local/lib/python3.7/dist-packages (from opendartreader) (1.3.5)
Requirement already satisfied: requests-file in /usr/local/lib/python3.7/dist-packages (from opendartreader) (1.5.1)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.19.2->opendartreader) (2.8.2)
Requirement already satisfied: numpy>=1.17.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.19.2->opendartreader) (1.19.5)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.19.2->opendartreader) (2018.9)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas>=0.19.2->opendartreader) (1.15.0)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests>=2.3.0->opendartreader) (2.10)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests>=2.3.0->opendartreader) (1.24.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests>=2.3.0->opendartreader) (2021.10.8)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests>=2.3.0->opendartreader) (3.0.4)

In [ ]:
import OpenDartReader

api_key = 'b474f083c000d49694833c96e6372fdec4df3912'

dart = OpenDartReader(api_key)

In [ ]:
# 삼성전자 2021-07-12 하루 동안 공시 목록
dart.list('005930', end='2021-7-12')

   corp_code corp_name stock_code corp_cls  ...        rcept_no  flr_nm  rcept_dt rm
0   00126380      삼성전자     005930        Y  ...  20210707800054    삼성전자  20210707  유
1   00126380      삼성전자     005930        Y  ...  20210706800475    삼성전자  20210706  유
2   00126380      삼성전자     005930        Y  ...  20210705800437    삼성전자  20210705  유
3   00126380      삼성전자     005930        Y  ...  20210629000190     안규리  20210629
4   00126380      삼성전자     005930        Y  ...  20210629000122     박창진  20210629
..       ...       ...        ...      ...  ...             ...     ...       ... ..
31  00126380      삼성전자     005930        Y  ...  20000404000429    삼성전자  20000404
32  00126380      삼성전자     005930        Y  ...  20000401000031    삼성전자  20000401
33  00126380      삼성전자     005930        Y  ...  20000320000124  삼일회계법인  20000320
34  00126380      삼성전자     005930        Y  ...  19990824000003    삼성전자  19990824
35  00126380      삼성전자     005930        Y  ...  19990626000007    삼성전자  19990626  연

[5336 rows x 9 columns]

In [ ]:
dart.list(start='2021-07-05', end='2021-07-12', final=False)

   corp_code            corp_name stock_code  ...   flr_nm  rcept_dt  rm
0   00605522                  소룩스     290690  ...      소룩스  20210705  코정
1   01118139                  타스컴     336040  ...      타스컴  20210706   정
2   00977377                 에이비온     203400  ...     에이비온  20210712   정
3   01490990  케이비국민카드제칠차유동화전문유한회사             ...  케이비국민카드  20210712   정
4   01388604  케이비국민카드제육차유동화전문유한회사             ...  케이비국민카드  20210712   정
..       ...                  ...        ...  ...      ...       ...  ..
92  00685935              메리츠자산운용             ...    금융감독원  20210705
93  00243553               신한자산운용             ...    금융감독원  20210705
94  00243553               신한자산운용             ...    금융감독원  20210705
95  00405463            에이치디씨자산운용             ...    금융감독원  20210705
96  00176914                 다우기술     023590  ...     다우기술  20210705

[3597 rows x 9 columns]